### ISSUE TITLE
Obfuscation Documentation

### ISSUE THREAD

**Issue by wolframm** [petercinibulk/envied#17]
Could you expand on the documentation of the `obfuscate`-option? As far as I understand: 

The `obfuscate` option allows having a single `Envied` class for both frontend and backend apps, because sensitive environment variables such as passwords, which should only ever be available to backend apps, are only decrypted if they are actually accessed by the app's source code.

Is this correct?

**Comment by petercinibulk** [comment]
First off, I recommend storing all secrets on the backend side and making all queries through an authenticated source.

The obfuscate option allows the field to be "encrypted." The encryption key will still be available but it is one step to make it harder for bad actors to scrape your app for any keys.

Again, you should try not to keep secrets in a client app because a bad actor can obtain those. The obfuscation option makes it just a little harder to do so.

**Comment by wolframm** [comment]
OK. Thank you for clarifying this. Perhaps it would be useful for others if you include your warning in the documentation on pub.dev.
